version: '3.1'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: node
    links:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: restdb
      MONGO_NON_ROOT_USERNAME: user
      MONGO_NON_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - ./mongoinit:/docker-entrypoint-initdb.d
  
